data:
  train_batch_size: 256
  micro_batch_size_per_gpu: 4  # this is also val batch size
  train_files: ~/data/gsm8k/train.parquet
  val_files: ~/data/gsm8k/test.parquet
  prompt_key: question
  response_key: answer
  max_length: 1024
  middle_strategy: line
  middle_line_num: null
  truncation: error
  balance_dp_token: False
  chat_template: null
  fim_rate: 1
  resp_cutoff_ratio: 0.0
  # for merging strategies
  merge_prob: 0.5
  max_delete: 64
  merge_schedule: dynamic_inverse
  use_uniform_merge_prob: 0.5
model:
  partial_pretrain: ~/models/gemma-1.1-7b-it
  fsdp_config:
    wrap_policy:
      min_num_params: 0
    cpu_offload: False
    offload_params: False
  external_lib: null
  enable_gradient_checkpointing: False
  trust_remote_code: False
  lora_rank: 0  # Set to positive value to enable LoRA (e.g., 32)
  lora_alpha: 16  # LoRA scaling factor
  target_modules: all-linear  # Target modules for LoRA adaptation
  use_liger: False
optim:
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.1
  clip_grad: 1.0
ulysses_sequence_parallel_size: 1
use_remove_padding: False
trainer:
  default_local_dir: /tmp/sft_model
  default_hdfs_dir: hdfs://tmp/experiments/gsm8k/gemma-1.1-7b-it/ # change the hdfs path here
  resume_path: null
  resume_training: False
  project_name: gsm8k-sft
  experiment_name: test
  total_epochs: 3
  total_training_steps: null
  logger: ['console']
  seed: 1
  save_checkpoint_steps: 10
diffusion:
  diffusion_steps: 64  # timesteps of diffusion models.
  decoding_strategy: stochastic0.5-linear  # <topk_mode>-<schedule>
  token_reweighting: false  # use focal loss for token-level reweighting
  alpha: 0.25  # for focal loss
  gamma: 2  # for focal loss
  time_reweighting: original  # use focal loss for token-level reweighting
  topk_decoding: false  # use focal loss for token-level reweighting
  cart_p: 0.1
  weight_eos: false
